### ISSUE TITLE
Licensing?

### ISSUE THREAD

**Issue by AnOpenSauceDev** [open-ribbon/open-ribbon#9]
Currently both this repository and [the documentation](https://github.com/open-ribbon/documentation) don't have an open-source license. I propose doing something similar to the [Super Mario 64 Decompilation](https://github.com/n64decomp/sm64), and go with a license such as CC0 or MIT. Otherwise, it might be a legal issue to port to PC/release modded ROMs based off this project for anyone outside of the organization.

**Comment by unclamped** [comment]
right, didn't notice at all. may I suggest the New BSD license? here's an example coming from one of my own projects:
https://github.com/unclamped/escmb-noticias-bot/blob/main/LICENSE

**Comment by mkst** [comment]
I think it's a bad idea to try and claim any ownership of the code. If you write any tooling then slap an MIT or similar license in the `tools/` dir

**Comment by AnOpenSauceDev** [comment]
> I think it's a bad idea to try and claim any ownership of the code. If you write any tooling then slap an MIT or similar license in the `tools/` dir

Yeah, it is a bit difficult because of the whole nature of the decomp. Looking into this topic further it seems like you'd have to make this more "transformative" to constitute fair use, which i don't really think this is. I'll leave this open if anyone else wants to comment on this, but it seems like the code itself will have to stay unlicensed.

**Comment by AnOpenSauceDev** [comment]
The documentation has been given a license, which is probably the most that can be done at this time.
